name: Clean Build

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: 删除 Gradle 缓存
        run: rm -rf ~/.gradle/caches/

      - name: 删除 m2 缓存
        run: rm -rf ~/.m2/repository/

      - name: 删除 ccache 缓存
        run: rm -rf ~/.ccache/

  cleanup-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 清理所有失敗的 Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
          delete_run_by_conclusion_pattern: 'failure,skipped'